# auth testing

POST http://127.0.0.1:8000/signup 
Content-Type: application/json

{ "username": "elieSawmaawad", "first_name": "Elie", "last_name": "Sawma Awad", "password": "TestCase1!89", "email": "elie.sawmaawad@icloud.com", "phone_number": 75655699}

###

POST http://127.0.0.1:8000/login 
Content-Type: application/json

{ "login_credential": "firsttester@gmail.com", "password": "Abc@123"}

###

POST http://127.0.0.1:8000/user/sendConfirmationEmail
Content-Type: application/json
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMxNTAwMTUyLCJpYXQiOjE3MzE0OTkyNTIsImp0aSI6IjZjMjJkNmM4NGFlMjQ0OTg4YjFhMmM3NDgxYjRmNWIzIiwidXNlcl9pZCI6MX0.BYtvqBT29OlOD0MFTBGm1A5hR0x6c3qR2ajedO-RcUs
